import React from 'react'
import TopPackageComponents from '@/components/TopPackageComponents'
import { SpecialPackage } from '@/types/TourType';

export default function page() {
    const seasons = ['Semua', 'Lebaran', 'Liburan Sekolah', 'Natal & Tahun Baru', 'Long Weekend'];

    const packages: SpecialPackage[] = [
        {
            id: 1,
            title: 'Lebaran di Desa Manud Jaya',
            subtitle: 'Rasakan kehangatan Idul Fitri bersama masyarakat desa dengan tradisi halal bi-halal dan kuliner khas lebaran nusantara.',
            image: '/assets/e50bd774-982a-4206-b5b9-3ace3c9c8f27-gobi_gallery1.jpg',
            price: 2850000,
            originalPrice: 3800000,
            discount: 25,
            badge: 'Spesial Lebaran',
            badgeEmoji: '🌙',
            gradient: 'linear-gradient(135deg, #1B8A5A, #34D399)',
            durationDays: 4,
            groupSize: '8–12 orang',
            rating: 4.9,
            reviews: 127,
            highlights: ['Halal bi-halal bersama warga', 'Kuliner opor & ketupat tradisional', 'Pertunjukan Angklung spesial', 'Jelajah alam pagi hari'],
            season: 'Lebaran',
            dateRange: '30 Mar – 3 Apr 2026',
            limitedSlots: 5,
        },
        {
            id: 2,
            title: 'Liburan Sekolah: Petualangan Alam',
            subtitle: 'Program edukasi alam untuk keluarga — anak-anak belajar bercocok tanam, mengenal hewan ternak, dan bermain di sungai.',
            image: '/assets/e4d847b7-3667-467f-992c-05ff8a23fde6-c6a9139fa9f5509fd47ec9df5236f669.jpg',
            price: 1950000,
            originalPrice: 2500000,
            discount: 22,
            badge: 'Liburan Sekolah',
            badgeEmoji: '🎒',
            gradient: 'linear-gradient(135deg, #2563EB, #60A5FA)',
            durationDays: 3,
            groupSize: '6–15 orang',
            rating: 4.8,
            reviews: 89,
            highlights: ['Workshop berkebun organik', 'Bermain sungai & arung jeram mini', 'Wisata edukasi peternakan', 'Camping under the stars'],
            season: 'Liburan Sekolah',
            dateRange: '20 Jun – 31 Jul 2026',
            limitedSlots: 12,
        },
        {
            id: 3,
            title: 'Natal & Tahun Baru di Pegunungan',
            subtitle: 'Rayakan pergantian tahun di udara sejuk pegunungan, nikmati api unggun, live music akustik, dan pesta kembang api.',
            image: '/assets/38826e03-83a4-482e-a720-492ac8bfaef5-cover_culture.jpg',
            price: 3200000,
            originalPrice: 4200000,
            discount: 24,
            badge: 'Natal & Tahun Baru',
            badgeEmoji: '🎄',
            gradient: 'linear-gradient(135deg, #DC2626, #F59E0B)',
            durationDays: 5,
            groupSize: '10–20 orang',
            rating: 4.9,
            reviews: 156,
            highlights: ['Pesta api unggun malam tahun baru', 'Live music akustik di alam', 'Gala dinner kuliner nusantara', 'Sunrise hike gunung'],
            season: 'Natal & Tahun Baru',
            dateRange: '28 Des 2026 – 2 Jan 2027',
            limitedSlots: 8,
        },
        {
            id: 4,
            title: 'Long Weekend: Cultural Escape',
            subtitle: 'Weekend getaway singkat — jelajahi desa budaya, ikut kelas membatik, dan nikmati spa tradisional jamu.',
            image: '/assets/7a750ea3-4682-4260-acf4-eb18b2ccc0a0-fa723100cbf6b45c3c8aa40ca4adf9b82222.jpg',
            price: 1450000,
            originalPrice: 1800000,
            discount: 19,
            badge: 'Long Weekend',
            badgeEmoji: '🏖',
            gradient: 'linear-gradient(135deg, #7C3AED, #C084FC)',
            durationDays: 2,
            groupSize: '4–8 orang',
            rating: 4.7,
            reviews: 63,
            highlights: ['Workshop membatik & menenun', 'Spa jamu tradisional', 'Kuliner pasar tradisional', 'Fotografi desa pagi hari'],
            season: 'Long Weekend',
            dateRange: 'Setiap long weekend 2026',
            limitedSlots: 6,
        },
        {
            id: 5,
            title: 'Lebaran: Tradisi Desa Penglipuran',
            subtitle: 'Lebaran spesial di desa terbersih Bali — ikut serta dalam tradisi ngejot dan saling berbagi antar warga.',
            image: '/assets/9b4e5aa3-5ec7-4c73-b146-e0f45b9eff94-mistakes_Gallery_road.jpg',
            price: 3500000,
            originalPrice: 4500000,
            discount: 22,
            badge: 'Spesial Lebaran',
            badgeEmoji: '🌙',
            gradient: 'linear-gradient(135deg, #059669, #6EE7B7)',
            durationDays: 5,
            groupSize: '6–10 orang',
            rating: 4.9,
            reviews: 94,
            highlights: ['Tradisi ngejot antar warga', 'Kuliner khas Bali', 'Tur arsitektur tradisional', 'Upacara keagamaan lokal'],
            season: 'Lebaran',
            dateRange: '30 Mar – 4 Apr 2026',
            limitedSlots: 4,
        },
        {
            id: 6,
            title: 'Liburan Keluarga: Wae Rebo Explorer',
            subtitle: 'Ajak si kecil menjelajah rumah adat Mbaru Niang di atas awan — pengalaman menginap di rumah tradisional Flores.',
            image: '/assets/22f1c083-1bb1-4fb6-a963-93b1e67341ef-36eb93d315a100c3d3098747caaa90d33.jpg',
            price: 4200000,
            originalPrice: 5500000,
            discount: 24,
            badge: 'Liburan Sekolah',
            badgeEmoji: '🎒',
            gradient: 'linear-gradient(135deg, #0891B2, #67E8F9)',
            durationDays: 6,
            groupSize: '8–14 orang',
            rating: 5.0,
            reviews: 201,
            highlights: ['Menginap di Mbaru Niang', 'Trekking hutan tropis', 'Belajar tenun ikat dari mama-mama', 'Sunset di puncak Todo'],
            season: 'Liburan Sekolah',
            dateRange: '20 Jun – 31 Jul 2026',
            limitedSlots: 7,
        },
    ];
    return (
        <TopPackageComponents packages={packages} seasons={seasons} />
    )
}
