import CareerComponents from '@/components/CareerComponents'
import { JobListing } from '@/types/CareerType';

export default function page() {
    const jobs: JobListing[] = [
        {
            id: 1,
            title: 'Petugas Keamanan Wisata',
            department: 'Tim Keamanan',
            departmentEmoji: '🛡️',
            gradient: 'linear-gradient(135deg, #1E40AF, #60A5FA)',
            type: 'Penuh Waktu',
            location: 'Desa Manud Jaya, Bandung Barat',
            salary: 'Rp 3.500.000 – Rp 4.500.000 / bulan',
            deadline: '15 April 2026',
            postedDate: '1 Maret 2026',
            slots: 2,
            summary: 'Kami mencari petugas keamanan yang bertanggung jawab untuk menjaga keselamatan dan kenyamanan wisatawan selama berada di kawasan Desa Wisata Manud Jaya. Posisi ini membutuhkan individu yang sigap, ramah, dan memiliki kemampuan komunikasi yang baik.',
            responsibilities: [
                'Melakukan patroli rutin di area wisata, perkebunan teh, dan jalur trekking',
                'Memastikan keamanan wisatawan selama aktivitas outdoor seperti river tubing dan camping',
                'Mengawasi area parkir dan pintu masuk kawasan wisata',
                'Berkoordinasi dengan tim pemandu untuk memastikan keselamatan di rute perjalanan',
                'Memberikan pertolongan pertama dan evakuasi jika terjadi keadaan darurat',
                'Membuat laporan harian terkait keamanan dan insiden',
            ],
            requirements: [
                { label: 'Pria/Wanita, usia 22–40 tahun' },
                { label: 'Pendidikan minimal SMA/SMK sederajat' },
                { label: 'Pengalaman minimal 1 tahun di bidang keamanan (diutamakan)' },
                { label: 'Memiliki sertifikat pelatihan keamanan atau Gada Pratama (nilai tambah)' },
                { label: 'Sehat jasmani dan rohani, tidak buta warna' },
                { label: 'Mampu berenang dan berjalan di medan pegunungan' },
                { label: 'Berdomisili di sekitar Bandung Barat (diutamakan)' },
            ],
            benefits: [
                { emoji: '💰', label: 'Gaji pokok + tunjangan makan & transport' },
                { emoji: '🏥', label: 'BPJS Kesehatan & Ketenagakerjaan' },
                { emoji: '🏕️', label: 'Akomodasi gratis di area desa wisata' },
                { emoji: '📚', label: 'Pelatihan SAR & P3K berkala' },
                { emoji: '🎯', label: 'Bonus kinerja bulanan' },
                { emoji: '🌿', label: 'Lingkungan kerja di alam terbuka' },
            ],
            qualifications: [
                'Memiliki kemampuan bela diri dasar',
                'Mampu berkomunikasi dalam Bahasa Indonesia & Sunda',
                'Tidak memiliki catatan kriminal',
                'Bersedia bekerja shift dan di hari libur',
            ],
            workSchedule: 'Shift: 06.00–14.00 / 14.00–22.00 WIB, 6 hari kerja, 1 hari libur (rolling)',
            contact: 'karir@desamanudjaya.id',
        },
        {
            id: 2,
            title: 'Staff Customer Service & Reservasi',
            department: 'Tim Bantuan & Layanan',
            departmentEmoji: '🤝',
            gradient: 'linear-gradient(135deg, #7C3AED, #A78BFA)',
            type: 'Penuh Waktu',
            location: 'Desa Manud Jaya, Bandung Barat',
            salary: 'Rp 3.000.000 – Rp 4.000.000 / bulan',
            deadline: '20 April 2026',
            postedDate: '1 Maret 2026',
            slots: 1,
            summary: 'Posisi ini bertanggung jawab mengelola reservasi wisatawan, menjawab pertanyaan melalui berbagai kanal komunikasi, dan memastikan pengalaman pelayanan yang memuaskan dari awal hingga akhir kunjungan.',
            responsibilities: [
                'Mengelola reservasi dan booking paket wisata melalui website, WhatsApp, dan telepon',
                'Memberikan informasi lengkap tentang paket wisata, harga, dan ketersediaan jadwal',
                'Menangani keluhan dan feedback wisatawan dengan cepat dan profesional',
                'Mengkoordinasikan jadwal kunjungan dengan tim pemandu dan logistik',
                'Mengelola database wisatawan dan laporan reservasi bulanan',
                'Membantu wisatawan selama berada di area wisata jika diperlukan',
            ],
            requirements: [
                { label: 'Pria/Wanita, usia 20–35 tahun' },
                { label: 'Pendidikan minimal D3 (Pariwisata/Komunikasi/Manajemen diutamakan)' },
                { label: 'Pengalaman minimal 1 tahun di bidang customer service atau hospitality' },
                { label: 'Mampu mengoperasikan komputer dan aplikasi office' },
                { label: 'Memiliki kemampuan komunikasi yang sangat baik' },
                { label: 'Mampu berbahasa Inggris dasar (aktif lisan & tulisan)' },
                { label: 'Teliti, sabar, dan berorientasi pada kepuasan pelanggan' },
            ],
            benefits: [
                { emoji: '💰', label: 'Gaji pokok + insentif per booking' },
                { emoji: '🏥', label: 'BPJS Kesehatan & Ketenagakerjaan' },
                { emoji: '💻', label: 'Fasilitas laptop & pulsa komunikasi' },
                { emoji: '📚', label: 'Pelatihan hospitality & digital marketing' },
                { emoji: '🎯', label: 'Bonus kinerja berdasarkan target' },
                { emoji: '☕', label: 'Snack & makan siang di kantor' },
            ],
            qualifications: [
                'Familiar dengan media sosial dan platform booking online',
                'Memiliki pengalaman menggunakan CRM atau sistem reservasi (nilai tambah)',
                'Berpenampilan rapi dan menarik',
                'Bersedia bekerja di weekend saat high season',
            ],
            workSchedule: 'Senin–Sabtu, 08.00–16.00 WIB (fleksibel saat high season)',
            contact: 'karir@desamanudjaya.id',
        },
        {
            id: 3,
            title: 'Koordinator Logistik & Perlengkapan',
            department: 'Tim Bantuan & Layanan',
            departmentEmoji: '🤝',
            gradient: 'linear-gradient(135deg, #7C3AED, #A78BFA)',
            type: 'Penuh Waktu',
            location: 'Desa Manud Jaya, Bandung Barat',
            salary: 'Rp 3.500.000 – Rp 5.000.000 / bulan',
            deadline: '25 April 2026',
            postedDate: '5 Maret 2026',
            slots: 1,
            summary: 'Bertanggung jawab atas pengelolaan logistik, perlengkapan, dan transportasi untuk mendukung operasional wisata sehari-hari. Posisi ini membutuhkan individu yang terorganisir, proaktif, dan memiliki pengalaman di bidang logistik atau manajemen supply chain.',
            responsibilities: [
                'Mengelola inventori perlengkapan wisata (tenda, alat camping, pelampung, dll.)',
                'Mengkoordinasikan transportasi wisatawan dari titik penjemputan ke desa',
                'Memastikan ketersediaan dan kondisi perlengkapan outdoor selalu prima',
                'Mengelola vendor dan supplier untuk kebutuhan operasional',
                'Menyusun laporan inventori dan pengadaan bulanan',
                'Berkoordinasi dengan tim pemandu untuk kebutuhan logistik per trip',
                'Mengelola armada kendaraan operasional desa wisata',
            ],
            requirements: [
                { label: 'Pria/Wanita, usia 25–40 tahun' },
                { label: 'Pendidikan minimal D3 (Logistik/Manajemen/Teknik diutamakan)' },
                { label: 'Pengalaman minimal 2 tahun di bidang logistik atau operasional' },
                { label: 'Memiliki SIM A dan SIM C aktif' },
                { label: 'Mampu mengoperasikan komputer dan software inventori' },
                { label: 'Memiliki kemampuan negosiasi dengan vendor' },
                { label: 'Sehat jasmani, mampu mengangkat beban hingga 20 kg' },
            ],
            benefits: [
                { emoji: '💰', label: 'Gaji pokok + tunjangan transportasi' },
                { emoji: '🏥', label: 'BPJS Kesehatan & Ketenagakerjaan' },
                { emoji: '🏕️', label: 'Akomodasi di area desa wisata' },
                { emoji: '🚗', label: 'Fasilitas kendaraan operasional' },
                { emoji: '📚', label: 'Pelatihan manajemen logistik' },
                { emoji: '🎯', label: 'Bonus efisiensi operasional' },
            ],
            qualifications: [
                'Familiar dengan sistem inventory management',
                'Memiliki jaringan vendor perlengkapan outdoor (nilai tambah)',
                'Mampu bekerja di bawah tekanan saat high season',
                'Memiliki kemampuan problem-solving yang baik',
            ],
            workSchedule: 'Senin–Sabtu, 07.00–15.00 WIB (on-call saat ada trip)',
            contact: 'karir@desamanudjaya.id',
        },
    ];
    return (
        <CareerComponents jobs={jobs} />
    )
}
